# Build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Runtime stage
FROM nginx:alpine

# After running npm run build, verify the generated directory under dist/. "ls -R dist"
#COPY --from=build /app/dist/<project-name>/browser /usr/share/nginx/html

COPY --from=build /app/dist/proshare-web/browser/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# docker run -d -p 4200:80 --name proshare-web proshare-web