name: Build, Push and Scan Image

on:
  workflow_run:
    workflows:
      - Security CI
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  build_push_scan_image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12.4"]

    steps:
      - name: Checkout Security CI commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          pytest addition.py

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Verify
        run: |
          echo "Image: $IMAGE"
          echo "Commit: $SHORT_SHA"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.SHORT_SHA }}
#            ghcr.io/${{ github.repository }}:latest
#            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE }}:${{ env.SHORT_SHA }}
          #image-ref: ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'