name: Security CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6


      ### Secret Scan ###
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ### SAST ###
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Analyze
        uses: github/codeql-action/analyze@v4

      ### Dependency Scan ##
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: .
          scanners: vuln,secret
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table
          skip-dirs: src/__pycache__